# Left half display (central). En la rama niceepaper es una nice!view de
# tinta electronica, pero los widgets son los mismos del modulo nice-oled.
# Bongo Cat aporreando al ritmo del tecleo (WPM).
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
